### ISSUE TITLE
can’t create a new session

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/Chums#147]
can’t create a new session….I click on groups, worship service, and then I click sessions… it doesn’t give me the option to view past sessions or add a new session…

**Comment by pranavmalvawala** [comment]
Thanks for creating an issue, @mbyrdLCS. I will take take a look into this and will get back to you in few hours

**Comment by pranavmalvawala** [comment]
![Capture](https://user-images.githubusercontent.com/42204892/105868649-68e32700-601c-11eb-8054-e1eb30d8dd62.JPG)

I understand, there used to be button here on the right, where we could view and create new sessions

**Comment by mbyrdLCS** [comment]
Yes, I remember there was a button on the right where we could view and create new sessions.

**Comment by pranavmalvawala** [comment]
Yes, you are right, no worries, I'll restore it once I get a signal to go

**Comment by jzongker** [comment]
This is fixed now.  The code to check if you have access to perform this action was looking at the wrong api (Membership vs Attendance)
