### ISSUE TITLE
Make nav items overflow into dropdown menu

### ISSUE THREAD

**Issue by LiveChurchSolutions** [LiveChurchSolutions/Chums#26]
Right now there are nav items that are manually set to appear in the navbar on desktop and drop down on mobile.  Since there's still not enough room on desktop, there's one more nav item (reports) that's manually set to appear in the dropdown on both.  This isn't a good way to handle things.  Especially since each user will have different menu items depending on their access.

Update the menu so that however many menu items will fit, show up in the nav bar and whatever won't fit shows up in the drop down.

**Comment by hambali999** [comment]
Hey! Can i work on this? please assigned me to work for this to earn the hacktoberfest 2020 💯 :)

**Comment by LiveChurchSolutions** [comment]
Absolutely.  I would love the help!
