### ISSUE TITLE
Automate testing

### ISSUE THREAD

**Issue by LiveCSDev** [LiveChurchSolutions/Chums#33]
We have a [number of cypress tests](https://github.com/LiveChurchSolutions/Chums/tree/master/CypressTests) currently.  I'd like for these to automatically run whenever changes are merged into master and trigger a notification of some type if they fail.

**Comment by Levi-Huynh** [comment]
Looking into this, but GH workflows can run  workflows/actions for repos as scheduled events..

https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events. The scheduler is pretty granular & can be ran within certain cycles (minutes, hours, day, month, weekly etc)

for example:
` on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *' 
`

is every night at midnight.

We might be able to combine it with GitHub actions to check into the Chums repo, and run testing scripts within the repo. 

here's a really basic example using GH's starter workflow that tests a node project using npm (although I think we can customize to the cypress test files) 
https://www.freecodecamp.org/news/what-are-github-actions-and-how-can-you-automate-tests-and-slack-notifications/#part-1-automating-tests

& subscribe to repo workflow notifications or
use cypress's slack notifications for failed tests
https://docs.cypress.io/guides/dashboard/slack-integration.html#Install-the-Cypress-Slack-app
and set up a specific channel for that

just some thoughts starting out

**Comment by jzongker** [comment]
I think you're right.  In that case we can just run after commits to the "develop" and "master" branches instead of on a scheduled basis.  I think this will need to wait until #8 and #32 are complete.

**Comment by Alec13355** [comment]
@jzongker I opened a pr to run cypress tests on pushes to master. Let me know how you'd like to be notified. By default, I think any owners/maintainers on the repo will get an email when the job fails, and the actions tab will also record runs.

**Comment by jzongker** [comment]
Fixed via multiple commits from irandom4 .
