### ISSUE TITLE
initDB fails

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/Chums#66]
npm run initDb fails on the reports.sql file.  The sql will run ok outside of the tool though.  Find the cause and fix it.

**Comment by pranavmalvawala** [comment]
Thanks for the quick fix @sybiljas. I actually tried what you suggested @jzongker, copy the whole file in workbench and see if it executes there but it did not work cause the problem was in actual query. Anyway I've tested this and it works, I'm closing the issue.
