### ISSUE TITLE
Show a prompt when registering for a new church fails

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/Chums#72]
We might wanna consider showing some error message when registering for a new church fails.

![register-bug](https://user-images.githubusercontent.com/42204892/99878952-0e4dd900-2c2f-11eb-809b-fc8f19bdba16.JPG)
Right now it just kind of looks hanged. It continuously show _Registering. Please wait..._

expected flow:
- If an error has occurred in registering then lets enable the button again and let user give a chance to edit the details without refreshing the page.
- show an error message why it failed ( I'd consider showing the same message every time like _There was problem in registering your church, Please try again!_ since for user it doesn't matter why exactly it failed).

Let me know what you think @jzongker @LiveCSDev

**Comment by jzongker** [comment]
Yeah, definitely needs to be fixed.  There's only one expected error the API should return or "Invalid password" if an account already exists for that email address but the password doesn't match.  I think we should show a pretty error message stating that, and a second "unexpected error" type message for anything else.

**Comment by pranavmalvawala** [comment]
Agreed!

**Comment by pranavmalvawala** [comment]
@jzongker This one looks done to me. I checked it. it shows error if email is already registered and success on creation.

I think we can close this one
