### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by pranavmalvawala** [LiveChurchSolutions/Chums#73]
Lets add some more information about setting up all the project folders for development purpose.

_It is taking significant amount of time when I try to make both react and node setup work together. I think we should add more context about setup and ease it out for the next person_

I'd be happy to write the steps. Let me know your thoughts @jzongker @LiveCSDev.

**Comment by jzongker** [comment]
Yes.  Please do add any documentation you think would be helpful.

**Comment by pranavmalvawala** [comment]
Sure, once I get my setup working properly. I will write down all the steps that it took.

**Comment by pranavmalvawala** [comment]
@jzongker I think we don't have to update README anymore since it pretty much sums up the steps for setting up the project for development. I wanted to do this earlier cause I had a hard time setting up but then we found out that it was just a `groups` bug and we've fixed it in this [PR](https://github.com/LiveChurchSolutions/Chums/pull/76). Let me know what you think.

**Comment by jzongker** [comment]
Good deal.  Agreed.
