### ISSUE TITLE
PersonAdd is broken throught the app

### ISSUE THREAD

**Issue by jzongker** [LiveChurchSolutions/Chums#89]
The PersonAdd.tsx is a shared component that was updated to prompt to copy the address as part of issue #51 .  Although this does the job when adding users to a household, it broke the other uses of this component (adding users to Groups and adding users to Roles).  Move the addess copy code out of this component.  The code should go in hanldePersonAdd of HouseholdEdit.tsx instead.

My mistake for not catching this.  Issue #86 should prevent that from happening in the future.

**Comment by pranavmalvawala** [comment]
It is totally my fault, I should have checked the usage of components at different places before editing but yes I spotted this problem a couple of days back. I also created a detailed [issue](https://github.com/LiveChurchSolutions/Chums/issues/77) on this one in case you haven't noticed.

I will fix this one today, I should not take up much time.

**Comment by jzongker** [comment]
Closed as a duplicate of #77
